// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContainer: typeof import('./components/layout/objects/AppContainer.vue')['default']
    AppIcon: typeof import('./components/ui/AppIcon.vue')['default']
    AppNav: typeof import('./components/layout/navigation/AppNav.vue')['default']
    AppNavActions: typeof import('./components/layout/navigation/AppNavActions.vue')['default']
    AppNavMenu: typeof import('./components/layout/navigation/AppNavMenu.vue')['default']
    AppNavToggle: typeof import('./components/layout/navigation/AppNavToggle.vue')['default']
    LayoutNavigationAppNav: typeof import('./components/layout/navigation/AppNav.vue')['default']
    LayoutNavigationAppNavActions: typeof import('./components/layout/navigation/AppNavActions.vue')['default']
    LayoutNavigationAppNavMenu: typeof import('./components/layout/navigation/AppNavMenu.vue')['default']
    LayoutNavigationAppNavToggle: typeof import('./components/layout/navigation/AppNavToggle.vue')['default']
    LayoutObjectsAppContainer: typeof import('./components/layout/objects/AppContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAppIcon: typeof import('./components/ui/AppIcon.vue')['default']
  }
}
